language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 crdist"
  - pyflakes -x W crdist
script:
  - cd demo
  - python manage.py test
