language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
install:
  - pip install -q Django==$DJANGO
  - pip install -q -e .
script:
  - python demo/manage.py test
